USE [master]
GO
/****** Object:  Database [PlantVisit]    Script Date: 23-01-2025 15:09:11 ******/
CREATE DATABASE [PlantVisit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PlantVisit', FILENAME = N'C:\Users\milan\PlantVisit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PlantVisit_log', FILENAME = N'C:\Users\milan\PlantVisit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PlantVisit] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PlantVisit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PlantVisit] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PlantVisit] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PlantVisit] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PlantVisit] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PlantVisit] SET ARITHABORT OFF 
GO
ALTER DATABASE [PlantVisit] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PlantVisit] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PlantVisit] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PlantVisit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PlantVisit] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PlantVisit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PlantVisit] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PlantVisit] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PlantVisit] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PlantVisit] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PlantVisit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PlantVisit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PlantVisit] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PlantVisit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PlantVisit] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PlantVisit] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PlantVisit] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PlantVisit] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PlantVisit] SET  MULTI_USER 
GO
ALTER DATABASE [PlantVisit] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PlantVisit] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PlantVisit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PlantVisit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PlantVisit] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PlantVisit] SET QUERY_STORE = OFF
GO
USE [PlantVisit]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [PlantVisit]
GO
/****** Object:  Table [dbo].[BookingTable]    Script Date: 23-01-2025 15:09:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookingTable](
	[BookingID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[PlantID] [int] NULL,
	[VisitID] [int] NULL,
	[BookingDate] [date] NULL,
	[Capacity] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BookingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Facilities]    Script Date: 23-01-2025 15:09:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Facilities](
	[FacilitiesID] [int] NOT NULL,
	[FacilitiesName] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[FacilitiesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PFMapping]    Script Date: 23-01-2025 15:09:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PFMapping](
	[PFID] [int] NOT NULL,
	[PlantID] [int] NULL,
	[FacilitiesID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PFID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PlantList]    Script Date: 23-01-2025 15:09:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PlantList](
	[PlantID] [int] NOT NULL,
	[PlantName] [varchar](100) NOT NULL,
	[PlantDescription] [text] NULL,
	[PlantLocation] [varchar](200) NOT NULL,
	[PlantNumber] [varchar](20) NULL,
	[PlantEmail] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[PlantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserData]    Script Date: 23-01-2025 15:09:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserData](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserNumber] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VisitSlot]    Script Date: 23-01-2025 15:09:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VisitSlot](
	[VisitID] [int] NOT NULL,
	[PlantID] [int] NULL,
	[VisitTime] [time](7) NULL,
	[Capacity] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[VisitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BookingTable]  WITH CHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[PlantList] ([PlantID])
GO
ALTER TABLE [dbo].[BookingTable]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[UserData] ([UserID])
GO
ALTER TABLE [dbo].[BookingTable]  WITH CHECK ADD FOREIGN KEY([VisitID])
REFERENCES [dbo].[PlantList] ([PlantID])
GO
ALTER TABLE [dbo].[PFMapping]  WITH CHECK ADD FOREIGN KEY([FacilitiesID])
REFERENCES [dbo].[Facilities] ([FacilitiesID])
GO
ALTER TABLE [dbo].[PFMapping]  WITH CHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[PlantList] ([PlantID])
GO
ALTER TABLE [dbo].[VisitSlot]  WITH CHECK ADD FOREIGN KEY([PlantID])
REFERENCES [dbo].[PlantList] ([PlantID])
GO
USE [master]
GO
ALTER DATABASE [PlantVisit] SET  READ_WRITE 
GO
